# Generated by Django 6.0.1 on 2026-02-18 22:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data da Venda'),
            preserve_default=False,
        ),
    ]
