# Generated by Django 6.0.1 on 2026-02-19 02:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_data_venda'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='saldo_devedor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Saldo Devedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='venda',
            name='tipo_pagamento',
            field=models.CharField(choices=[('avista', 'À Vista'), ('parcelado', 'Parcelado')], default=1, max_length=20, verbose_name='Tipo de Pagamento'),
            preserve_default=False,
        ),
    ]
