# Generated by Django 6.0.2 on 2026-02-23 14:26

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('modelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(help_text='Formato: AAA1A23 ou AAA-1234', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Placa inválida. Use o formato AAA1A23 (Mercosul) ou AAA-1234 (Antigo).', regex='^[A-Z]{3}\\d[A-J0-9]\\d{2}$')])),
                ('ano', models.PositiveSmallIntegerField(default=2026, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(3000)])),
                ('cor', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, help_text='Preço do veículo em reais (ex.: 50000.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Preço')),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('VENDIDO', 'Vendido'), ('RESERVADO', 'Reservado'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=20)),
                ('modelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modelos.modelo')),
            ],
        ),
    ]
