# Generated by Django 6.0.2 on 2026-02-25 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
