# Generated by Django 6.0.2 on 2026-02-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_veiculo_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='veiculo',
            name='imagem_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/media/'),
        ),
    ]
