# Generated by Django 6.0.2 on 2026-02-26 18:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import veiculos.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_veiculo_imagem_veiculo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='veiculo',
            options={'ordering': ['-created_at'], 'verbose_name': 'Veículo', 'verbose_name_plural': 'Veículos'},
        ),
        migrations.AddField(
            model_name='veiculo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='veiculo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='veiculos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='ano',
            field=models.PositiveSmallIntegerField(default=veiculos.models.current_year, validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(3000)]),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='imagem_veiculo',
            field=models.ImageField(blank=True, null=True, upload_to='veiculos/'),
        ),
    ]
