# Generated by Django 6.0.1 on 2026-02-18 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_alter_veiculo_cor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
