# Generated by Django 6.0.2 on 2026-02-26 18:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_veiculo_options_veiculo_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='placa',
            field=models.CharField(help_text='Formato: AAA1A23 ou AAA-1234', max_length=8, unique=True, validators=[django.core.validators.RegexValidator(code='placa_invalida', message='Placa inválida. Use o formato AAA1A23 (Mercosul) ou AAA-1234 (Antigo).', regex='^[A-Z]{3}[0-9][A-Z0-9][0-9]{2}$|^[A-Z]{3}-[0-9]{4}$')]),
        ),
    ]
