# Generated by Django 6.0.1 on 2026-02-18 22:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0004_alter_veiculo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='preco',
            field=models.DecimalField(decimal_places=2, help_text='Preço do veículo em reais (ex.: 50000.00)', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
