# Generated by Django 6.0.1 on 2026-02-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0006_alter_veiculo_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='status',
            field=models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('VENDIDO', 'Vendido'), ('RESERVADO', 'Reservado'), ('MANUTENCAO', 'Manutenção')], default='DISPONIVEL', max_length=20),
        ),
    ]
