# Generated by Django 6.0.2 on 2026-02-23 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instituicao_financeira', models.CharField(max_length=100)),
                ('valor_financiado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('taxa_juros', models.DecimalField(decimal_places=2, max_digits=5)),
                ('parcelas', models.IntegerField()),
                ('data_inicio', models.DateField()),
                ('contrato', models.FileField(upload_to='contratos_financiamento/')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
    ]
