# Generated by Django 6.0.2 on 2026-02-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='email address'),
        ),
    ]
