# Generated by Django 6.0.2 on 2026-02-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, verbose_name='Endereço de Email'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='endereco_completo',
            field=models.TextField(help_text='Insira o endereço completo', verbose_name='Endereço Completo'),
        ),
    ]
