# Generated by Django 6.0.1 on 2026-02-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_alter_cliente_email_alter_cliente_endereco_completo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='endereco_completo',
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
