# Generated by Django 6.0.1 on 2026-02-19 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_remove_cliente_endereco_completo_cliente_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='sobrenome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
