# Generated by Django 6.0.1 on 2026-02-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0001_initial'),
        ('parcelas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='status',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagamento',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='parcelas.parcela'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
