# Generated by Django 6.0.1 on 2026-02-19 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0002_remove_pagamento_status_pagamento_metodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='forma_pagamento',
            field=models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=50),
        ),
    ]
