# Generated by Django 6.0.1 on 2026-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagamentos', '0003_alter_pagamento_forma_pagamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagamento',
            name='forma_pagamento',
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='metodo',
            field=models.CharField(choices=[('cartao_credito', 'Cartão de Crédito'), ('cartao_debito', 'Cartão de Débito'), ('boleto', 'Boleto Bancário'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro')], max_length=50),
        ),
    ]
