# Generated by Django 6.0.1 on 2026-02-19 02:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendas', '0003_venda_entrada_venda_saldo_devedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PEDENTE', 'Pendente'), ('PAGO', 'Pago'), ('ATRASADA', 'Atrasada')], default='PENDENTE', max_length=10)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='vendas.venda')),
            ],
        ),
    ]
