# Generated by Django 6.0.2 on 2026-02-26 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0002_auditlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logacesso',
            name='id',
        ),
        migrations.RemoveField(
            model_name='logsistema',
            name='id',
        ),
        migrations.AddField(
            model_name='logacesso',
            name='id_log',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='logsistema',
            name='id_log',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
